d_x: 4
d_yc: 30
d_yt: 30
learning_rate: 0.001
l2_coeff: 0.001
loss: mse
linear_window: 0
linear_shared_weights: false
use_revin: false
use_seasonal_decomp: false
verbose: true
max_seq_len: 11
start_token_len: 0
attn_factor: 5
d_model: 10
d_queries_keys: 4
d_values: 4
n_heads: 3
e_layers: 2
d_layers: 2
d_ff: 40
dropout_emb: 0.0
dropout_qkv: 0.0
dropout_ff: 0.0
dropout_attn_out: 0.0
dropout_attn_matrix: 0.0
pos_emb_type: abs
global_self_attn: full
local_self_attn: full
global_cross_attn: full
local_cross_attn: none
performer_kernel: relu
embed_method: spatio-temporal
performer_relu: true
performer_redraw_interval: 100
attn_time_windows: 1
use_shifted_time_windows: false
activation: gelu
norm: batch
use_final_norm: true
init_lr: 1.0e-10
base_lr: 0.001
warmup_steps: 1000
decay_factor: 0.8
initial_downsample_convs: 0
intermediate_downsample_convs: 0
class_loss_imp: 0.0001
recon_loss_imp: 0.0
time_emb_dim: 6
null_value: null
pad_value: null
use_val: true
use_time: true
use_space: true
use_given: true
recon_mask_skip_all: 1.0
recon_mask_max_seq_len: 5
recon_mask_drop_seq: 0.2
recon_mask_drop_standard: 0.1
recon_mask_drop_full: 0.05
