activation: gelu
attn_factor: 5
attn_time_windows: 1
base_lr: 0.001
class_loss_imp: 0.0001
d_ff: 40
d_layers: 2
d_model: 10
d_queries_keys: 4
d_values: 4
d_x: 4
d_yc: &id001 !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  BAAAAAAAAAA=
d_yt: *id001
decay_factor: 0.8
dropout_attn_matrix: 0.0
dropout_attn_out: 0.0
dropout_emb: 0.0
dropout_ff: 0.0
dropout_qkv: 0.0
e_layers: 2
embed_method: spatio-temporal
global_cross_attn: full
global_self_attn: full
init_lr: 1.0e-10
initial_downsample_convs: 0
intermediate_downsample_convs: 0
l2_coeff: 0.001
learning_rate: 0.001
linear_shared_weights: false
linear_window: 0
local_cross_attn: none
local_self_attn: full
loss: mse
max_seq_len: 16
n_heads: 2
norm: batch
null_value: null
pad_value: null
performer_kernel: relu
performer_redraw_interval: 100
performer_relu: true
pos_emb_type: abs
recon_loss_imp: 0.0
recon_mask_drop_full: 0.05
recon_mask_drop_seq: 0.2
recon_mask_drop_standard: 0.1
recon_mask_max_seq_len: 5
recon_mask_skip_all: 1.0
start_token_len: 0
time_emb_dim: 6
use_final_norm: true
use_given: true
use_revin: false
use_seasonal_decomp: false
use_shifted_time_windows: false
use_space: true
use_time: true
use_val: true
verbose: true
warmup_steps: 1000
